import { LoginModal, Navbar, RegisterModal, RentModal } from "@/app/components";
import { Nunito } from "next/font/google";
import ClientOnly from "./components/ClientOnly";
import "./globals.css";
import ToasterProvider from "./providers/ToasterProvider";
import { getCurrentUser } from "./actions";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <Navbar currentUser={currentUser} />
          <RegisterModal />
          <LoginModal />
          <RentModal />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
